#! /usr/bin/env python
# encoding: utf-8
# DC 2008
# Thomas Nagy 2010 (ita)

srcdir = '.'
blddir = 'build'

def options(opt):
	opt.tool_options('fakecc', tooldir='.')

def configure(conf):
	conf.check_tool('fakecc', tooldir='.')

def build(bld):
	bld(
		features = 'fakecc',
		source   = 'hello_main.a hello.a',
		target   = 'hello')
