#! /usr/bin/env python
top = '.'
out = 'bin'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')
	import os
	os.environ['JOBS'] = '1'
	conf.check_tool('nothreads', tooldir='.')

def build(bld):
	bld(features='cc cprogram', source='main.c', target='foo')

