#! /usr/bin/env python
# encoding: utf-8

srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('fakecc', tooldir=".")

def configure(conf):
	conf.check_tool('fakecc')

def build(bld):
	"try using:       waf --zones=task_gen"
	bld.new_task_gen(
		features = 'fakecc',
		#source = 'hello.a hello_main.a',
		source = 'hello_main.a hello.a',
		target = 'hello')
