#! /usr/bin/env python
# encoding: UTF-8
# Peter Forai
# Thomas Nagy, 2008

VERSION='0.0.1'
APPNAME='swig_test'
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('g++')
	opt.tool_options('python')

def configure(conf):
	conf.check_tool('g++ python')
	conf.check_tool('swig', tooldir='.')
	conf.check_swig_version('1.3.27')

def build(bld):
	obj = bld.create_obj('cxx', 'program', 'pyembed')
	obj.source = 'src1.cpp bind.swig'
	obj.target = 'swigdemo'
	obj.swig_flags = '-c++ -python -dump_classes'

def shutdown():
	import os, stat
	try:
		os.stat('build/default/swigdemo')
		os.popen('PYTHONPATH=$PYTHONPATH:build/default/ build/default/swigdemo')
	except:
		pass

