#! /usr/bin/env python
# encoding: UTF-8
# Petar Forai

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='swig_test'

# these variables are mandatory,
srcdir = '.'
blddir = 'build'

def init():
	pass

def set_options(opt):
	opt.tool_options('gcc')
	opt.tool_options('python')

def configure(conf):
	conf.check_tool('g++ python')
	#conf.check_tool('swig', tooldir='.')
	conf.check_swig_version('1.3.27')

	conf.env['CXXFLAGS']='-Wall -g -O0 -pipe'

def build(bld):
	obj = bld.create_obj('cxx','program','pyembed')
	obj.source = 'swigtooldemo.cpp swigtooldemo.swig'
	obj.target = 'swigdemo'
	obj.swigflags = '-c++ -python -dump_classes'

def shutdown():
	import os, stat
	try:
		os.stat('build/default/swigdemo')
		os.popen('PYTHONPATH=$PYTHONPATH:build/default/ build/default/swigdemo')
	except:
		pass

