#!/usr/bin/env python
# encoding: utf-8

def build(bld):
	# to compile in c or c++ mode, uncomment the appropriate line below:
	#mode = 'cxx'
	mode = 'cc'

	obj = bld.new_task_gen(
		features = 'cprogram ' + mode,
		includes = '.',
		target = 'calc',
		uselib = 'CALC')
	obj.find_sources_in_dirs('.')

	# sources may be given one by one, like this
	#obj.source='''
	#main.c
	#calc.l
	#calc.y
	#'''

