#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# Creates a simple program
# This file is not a module, and all the code
# from it will be executed upon compile step
#
# This is really the content of a "def build(bld):" function definition
#
# By contrast, only functions can be defined in a wscript
#

obj = bld.create_obj('cxx', 'program')
obj.source='''
main.cpp
'''
obj.includes     = '. ../src'
obj.uselib_local = 'tony john'
obj.target       = 'testprogram2'

