#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010

srcdir = '.'
blddir = 'out'

import Scripting, Options

def configure(conf):
    conf.check_tool('gcc')

def build(bld):
	bld.install_files('/tmp/foo/', 'wscript')
	bld.new_task_gen(features='cc cprogram', target='foo', source='k.c')

def dist(ctx):
	Scripting.commands.insert(0, 'package')
	Scripting.commands.insert(0, 'install')
	Options.options.destdir = '/tmp/foo'

def package(ctx):
	print("packaging")

