#! /usr/bin/env python
# encoding: utf-8
# Thomas Frauendorfer, 2010

VERSION='0.0.1'
APPNAME='ruby_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def set_options(opt):
    opt.tool_options('ruby')
    opt.tool_options('compiler_cc')

def configure(conf):
    conf.check_tool('compiler_cc')
    conf.check_tool('ruby')

    # check for ruby
    conf.check_ruby_version((1,8,0))
    conf.check_ruby_ext_devel()

def build(bld):

    # Build a ruby extension module
    obj = bld(
        features = 'cc cshlib rubyext',
        source = 'rb_mytest.c',
        target = 'mytest_ext',
        install_path = '${ARCHDIR_RUBY}')

    bld.install_files('${LIBDIR_RUBY}', 'Mytest.rb')
