#! /usr/bin/env python
# encoding: utf-8

"""
This wscript demonstrates how to configure dependent library.
"""
import Options
import os.path

srcdir = '.'
blddir = '../out'

def configure(conf):
    conf.check_tool('gcc')
    lib_path = os.path.join(Options.launch_dir, '..', 'out', 'default')

    # This one is going to fail
    conf.check(lib='a', path=[lib_path], errmsg="first trial failed due to dependencies between libraries")

    # This one should work
    conf.check(lib='a', path=[lib_path], uselib=['b'], errmsg="This one should have not fail!!! :(", mandatory=True)

    # Note: order matters - if you have many libs in lib_configurator.libs, you should provide independent libraries first.

def build(bld):
    pass

def set_options(opt):
    pass
