#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

VERSION='0.7.4c'
APPNAME='waf'

demos = ['qt4', 'tex', 'cpp', 'ocaml', 'kde3']

import Params, os, sys
if Params.g_options.prepare:
	print "preparing the cpp demo (run ./waf --cleanup to remove)"
	print "cd to demos/cpp/ and execute waf there (there other demos, not all are ready)"
	for d in demos:
		ret = os.popen("ln -s ../../wafadmin ./demos/%s/wafadmin && cp setenv.bat waf.py ./demos/%s/" % (d,d))
	sys.exit(0)
elif Params.g_options.cleanup:
	print "cleaning up the demo folders"
	for d in demos:
		ret = os.popen("rm -f ./demos/%s/waf.py ./demos/%s/setenv.bat ./demos/%s/wafadmin" % (d,d,d))
	sys.exit(0)
elif Params.g_options.arch:
	print "preparing an archive of waf for use in custom projects"
	import Runner
	ex = Runner.exec_command
	mw = 'miniwaf-'+VERSION
	cmd = [
		"rm -rf %s/ %s.tar.bz2 && mkdir -p %s/wafadmin/Tools/" % (mw,mw,mw),
		"cp waf.py setenv.bat %s/ && cp wafadmin/*.py %s/wafadmin/" % (mw,mw),
		"cp wafadmin/Tools/*.py %s/wafadmin/Tools/" % mw,
		"rm -f %s/wafadmin/Test.py" % mw,
		#"pushd %s/wafadmin/ && perl -pi -e 's/^\s*#[^!].*$//' *.py && popd" % mw,
		#"pushd %s/wafadmin/ && perl -pi -e 's/^$//' *.py && popd" % mw,
		#"pushd %s/wafadmin/Tools && perl -pi -e 's/^\s*#[^!].*$//' *.py && popd" % mw,
		#"pushd %s/wafadmin/Tools && perl -pi -e 's/^$//' *.py && popd" % mw,
		"pushd %s && tar cjvf ../%s.tar.bz2 waf.py setenv.bat wafadmin" % (mw, mw),
		"rm -rf %s/" % mw,
	]

	for i in cmd:
		ret = ex(i)
		if ret:
			print "an error occured ",i
			sys.exit(0)
	print "your archive is ready"
	sys.exit(0)
else:
	print "run 'waf --help' to know more about allowed commands !"
	sys.exit(0)

