#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='cxx_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	conf.check_tool('compiler_cxx')
	conf.check(header_name='stdio.h', features='cxx cprogram')

def build(bld):
	bld.Program(source='main.cpp', target='app')
	if bld.cmd != 'clean':
		bld.log = open('test.log', 'w')
		bld.check(header_name='stdio.h', features='cxx cprogram')
		bld.log = None

