#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2009 (ita)

"""
TODO not finished
"""

VERSION='0.0.1'
APPNAME='cc_test'
srcdir = '.'
blddir = 'build'

def configure(conf):
	conf.check_tool('gcc')
	conf.check_tool('dirwatch', tooldir='.')

def build(bld):
	bld.new_task_gen(
		features='cc cprogram',
		source='main.c',
		target='test')

