#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

import os

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='msvc_test'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	# if a special version of visual studio is required
    # prefer version 8 over 9, but allow 9 if no 8 is found
	# conf.env['MSVC_VERSIONS'] = '8.0 9.0'
    # require 8 only
	# conf.env['MSVC_VERSIONS'] = '8.0'
    # X86 compiler only, no AMD64
	# conf.env['MSVC_TARGETS'] = 'x86'
	conf.check_tool('msvc')
	conf.check_libs_msvc('kernel32 user32', mandatory = True)



def build(bld):
	obj = bld.new_task_gen(features = 'cxx cstaticlib')
	obj.source = 'lib.cxx'
	obj.target = 'lib'

	obj = bld.new_task_gen(features = 'cxx cshlib')
	obj.source = 'dll.cxx'
	obj.target = 'dll'
	obj.defines = ['BUILDING_DLL']
	obj.uselib = 'KERNEL32 USER32'

	obj = bld.new_task_gen(features = 'cxx cprogram')
	obj.source = 'main.cxx resource.rc'
	obj.target = 'msvc_test'
	obj.uselib_local = ['dll', 'lib']

def shutdown():
	pass
