#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

VERSION='0.0.1'
APPNAME='cpp_test'

bld.set_dirs('.', '_build_')
bld.set_default_env('main.cache.py')

# cpp programs, shared and static libraries
from Common import cppobj

# process subfolders from here
add_subdir('src')

