#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# A c program that links using the GLIB library, defined in the configuration
obj = bld.create_obj('gnome', 'program')
#obj.source='''
#manager.xml.h. menus.c app.c hello.c icon.c
#'''
obj.find_sources_in_dirs('.') # take the sources in the current folder
obj.includes='.'
obj.uselib='GTK GNOME GNOMEUI DBUSGLIB'
obj.target='gnome-hello'
obj.add_dbus_file('manager.xml', 'test_prefix', 'glib-server')
obj.add_marshal_file('marshal.list', 'test_prefix', '--header')
obj.add_marshal_file('marshal.list', 'test_prefix', '--body')

# it is also possible to add tons if libraries
#obj.uselib='GTK GNOME GNOMEUI GLIB BONOBO BONOBOUI PRINT PRINTUI GLADE CANVAS XML GDK'

