#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005 (ita)

obj = qt4obj('program')
obj.source = 'window.cpp glwidget.cpp main.cpp textures.qrc'
obj.uselib = 'QT QTCORE QTGUI QTOPENGL'
obj.target = 'window'
obj.set_name('firstobj')
obj.include = 'src/test/ src/'
add_subdir('test')

