#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005 (ita)

def build(bld):
	obj = bld.createObj('qt4', 'program')

	## the sources can be given manually
	## or found automatically in the directories specified
	#obj.source = 'window.cpp glwidget.cpp main.cpp textures.qrc'

	obj.find_sources_in_dirs('.')
	obj.uselib = 'QT QTCORE QTGUI QTOPENGL'
	obj.target = 'window'
	obj.includes = 'test .'

	bld.add_subdirs('test')

