#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005 (ita)

def build(bld):
	obj = bld.createObj('qt4', 'program')
	obj.source = 'window.cpp glwidget.cpp main.cpp textures.qrc'
	obj.uselib = 'QT QTCORE QTGUI QTOPENGL'
	obj.target = 'window'
	obj.set_name('firstobj')
	obj.includes = 'test .'

	bld.add_subdir('test')

