#!/usr/bin/env python
# encoding: ISO8859-1
# Thomas Nagy, 2010

top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_tool('python')
	conf.check_python_headers()
	conf.check_tool('cython', tooldir='.')

def build(bld):
	bld(
		features = 'cc cshlib pyext',
		source   = 'src/test.pyx lib/lib.c',
		target   = 'test',
		includes = 'lib')

