#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

VERSION='0.0.1'
APPNAME='wafdocs'

import os, re, shutil
from waflib import Utils, Options, TaskGen

top = '.'
out = 'build'

re_xi = re.compile('''^(include|image)::([^.]*.(txt|png|eps))\[''', re.M)
def ascii_doc_scan(self):
	p = self.inputs[0].parent
	node_lst = [self.inputs[0]]
	seen = []
	depnodes = []
	while node_lst:
		nd = node_lst.pop(0)
		if nd in seen: continue
		seen.append(nd)

		code = nd.read()
		for m in re_xi.finditer(code):
			name = m.group(2)
			k = p.find_resource(name)
			if k:
				depnodes.append(k)
				if k.name.rfind('.txt') > 0:
					node_lst.append(k)
	return [depnodes, ()]

def set_options(opt):
	opt.add_option('--exe', action='store_true', default=False, help='Execute the program after it is compiled')

def configure(conf):
	conf.find_program('a2x', var='A2X')
	conf.find_program('asciidoc', var='ADOC')
	conf.find_program('dia', var='DIA')

def build(bld):
	for x in bld.path.ant_glob('*.dia'):
		bld(rule='${DIA} -t eps ${SRC} -e ${TGT}', source=x, target=x.change_ext('.eps'), ext_out=['.eps'])

	bld(rule='mkdir -p ${SRC[0].parent.get_bld().abspath()} && cp ${SRC} ${SRC[0].parent.get_bld().abspath()}',
		source=bld.path.ant_glob('callouts/*.png'))

	bld(rule='cp ${SRC} ${bld.bldnode.abspath()}', source='shishell.lang symbols.lang default.style lang.map', ext_out=['.eps'])

	bld(rule='${ADOC} -a icons=true -a iconsdir=. -a toc -n -d book -o ${TGT} -v -v ${SRC}',
		source='waf.txt', target='single.html', ext_in=['.eps'], name='single', scan=ascii_doc_scan)

	bld(rule='${A2X} -L -a toc --icons-dir=. -v -v --stylesheet=waf.css --icons -D ${gen.path.get_bld().abspath()} -d book -f pdf ${SRC}',
		source='waf.txt', target='waf.pdf', ext_in=['.eps'], name='single', scan=ascii_doc_scan)

	if Options.options.exe:
		def exe(ctx):
			p = Utils.pproc.Popen('firefox build/single.html', shell=True)
			p.wait()
		bld.add_post_fun(exe)

"""
Add the following to asciidoc/dblatex/asciidoc-dblatex.sty

\usepackage{color}
\usepackage{listings}
\definecolor{gray}{gray}{0.5}
\definecolor{plum}{rgb}{0.55078125,0.09765625,0.55859375}
\lstset{commentstyle=\color{plum}}
\lstdefinelanguage{shishell} {
  morekeywords={},
  sensitive=false,
  morecomment=[l]{\$}
}

Set the following values in asciidoc-dblatex.xsl:
  <xsl:param name="doc.publisher.show">0</xsl:param>
  ...
  <xsl:param name="latex.output.revhistory">0</xsl:param>
"""

