#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy 2008-2010

bld(
	features     = 'gnome_doc',
	doc_module   = 'cheese',
	doc_entities = 'legal.xml',
	doc_includes = '',
	doc_figures  = 'figures/cheese-screenshot.png figures/cheese-effects-screenshot.png',
	doc_linguas  = 'es fr',
)

