#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010 (ita)

"""

THE FOLLOWING IS A TESTCASE; DO NOT USE IT (YET)

"""

VERSION='0.0.1'
APPNAME='test'
top = '.'
out = 'build'

def configure(conf):
	conf.find_program('touch', mandatory=True)

def build(bld):
	bld(rule='mkdir -p default/a/b/c/ && touch default/a/b/c/foo.txt', name='blah')

	def printi(bld):
		print(' before update %r' % bld.path.ant_glob('**/*.txt', bld=True))
		bld.path.update_build_dir(bld.env)
		print(' after update  %r' % bld.path.ant_glob('**/*.txt', bld=True))

	bld.add_post_fun(printi)

