#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

import os

VERSION='0.0.2'
APPNAME='gcj_test'

srcdir = '.'
blddir = 'out'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('gcj', tooldir='.')

	#conf.check_tool('java')
	#conf.check_java_class('java.io.FileOutputStream')
	#conf.check_java_class('FakeClass')

def build(bld):
	bld.new_task_gen(
		features     = 'gcj',
		java_source  = '.*java$',
		source_root  = 'src',
		target       = 'test',
		gcjlinkflags = '--main=es.Hello',
		gcjonce      = True)

