#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008

import os
import Params

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='vala-gtk-example'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc vala')
	conf.check_pkg('glib-2.0', destvar='GLIB', vnum='2.10.0', mandatory=True)
	conf.check_pkg('gtk+-2.0', destvar='GTK', vnum='2.10.0', mandatory=True)

def build(bld):
	bld.add_subdirs('src')

def shutdown():
	pass
