#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

VERSION='0.0.1'
APPNAME='cpp_test'

bld.set_dirs('.', '_build_')
bld.set_default_env('main.cache.py')

Params.set_trace(1,1,1)
# cpp programs, shared and static libraries
from Common import cppobj

obj = cppobj('program')
obj.target = 'test'
obj.source = 'main.c'

