#! /usr/bin/env python
# encoding: utf-8
import Params
import os.path

obj = bld.create_obj('cpp', 'program')
obj.find_sources_in_dirs('.')
obj.uselib = 'CPPUNIT'
obj.uselib_local = 'unittestmain useless'
obj.includes = '../../src'
obj.unit_test = 1
obj.target = 'unit_test_program'

