#! /usr/bin/env python
# encoding: utf-8

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def configure(conf):
	conf.check_tool('gfortran', tooldir='.')
	conf.env['FCFLAGS'] = ['-Wall', '-W']

def build(bld):
	bld.new_task_gen(
		features = 'fortran fprogram',
		source = 'hello.f',
		target = 'hello')

	bld.new_task_gen(
		features = 'fortran fshlib',
		source = 'hello.f',
		target = 'hello')

	bld.new_task_gen(
		features = 'fortran fstaticlib',
		source = 'hello.f',
		target = 'hello')

	bld.new_task_gen(
		features = 'fortran',
		source = 'hello.f')


