#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

VERSION='0.0.1'
APPNAME='ocaml_test'

bld.set_dirs('.', '_build_')
bld.set_default_env('main.cache.py')

# we want to build caml programs
from Tools.Ocaml import ocamlobj

# process subfolders from here
add_subdir('src')

