#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005-2008 (ita)

# the following two variables are used by the target "waf dist"
VERSION = '0.0.1'
APPNAME = 'ocaml_test'

# these variables are mandatory,
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('ocaml')

def build(bld):
	# simple program

	obj = bld(
		features = 'ocaml',
		kind = 'all',
		includes = '.',
		target = 'camlprog')

	obj.find_sources_in_dirs('.')

