#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

import os
import Configure

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='ocaml_test'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'
cachedir = os.sep.join(['_build_', 'cache'])

# process subfolders from here
def build(bld):
	bld.add_subdir('src')

def set_options(opt):
	opt.add_option('--prefix', type='string', help='installation prefix', dest='prefix')
	opt.add_option('--destdir', type='string', help='destination for install (when creation rpms or debs)', dest='destdir')

def configure(conf):
	conf.checkTool(['Ocaml'])

