#!/usr/bin/env python
# encoding: utf-8

def options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	#conf.check_tool('compiler_cxx flex bison')
	conf.check_tool('compiler_cc flex bison')
	conf.env.LIB_CALC = ['fl']

def build(bld):
	# to compile in c or c++ mode, uncomment the appropriate line below:
	#mode = 'cxx'
	mode = 'cc'

	bld(
		features = 'cprogram ' + mode,
		includes = '.',
		source = 'calc.l calc.y main.c',
		target = 'calc',
		uselib = 'CALC')

