#! /usr/bin/env python
# encoding: utf-8
# Samuel Mendes, 2008 (lok)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='objc_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def configure(conf):
	conf.check_tool('gcc')
	conf.check_tool('gcc-objc', tooldir='.')
	#conf.check(framework_name='Foundation', framework_path='/Library/Frameworks')

def build(bld):
	main = bld(
		features     = 'cc cprogram',
		source       = 'test.m',
		target       = 'test_objc_program',
		uselib_local = 'teststaticlib',
		uselib       = 'FOUNDATION',
		)

	staticlib = bld(
		features     = 'cc cstaticlib',
		source       = 'HelloWorld.m',
		target       = 'teststaticlib',
		)

