#! /usr/bin/env python
# encoding: utf-8
# Samuel Mendes, 2008 (lok)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='objc_test'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('gcc')
	conf.check_tool('gcc-objc', tooldir='.')
	#conf.check(framework_name='Foundation', framework_path='/Library/Frameworks')

def build(bld):
	main = bld.new_task_gen('cc', 'program')
	main.source='test.m'
	main.target='test_objc_program'
	main.uselib_local='teststaticlib'
	main.uselib='FOUNDATION'

	staticlib = bld.new_task_gen('cc', 'staticlib')
	staticlib.source = 'HelloWorld.m'
	staticlib.target='teststaticlib'

