#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# Creates a simple program
# This file is not a module, and all the code
# from it will be executed upon compile step
#
# By contrast, only functions can be defined in wscripts
#

from Object import createObj

obj=createObj('cpp', 'program')
obj.source='''
main.cpp
'''
obj.includes='. src2'
obj.target='testprogram2'

