#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

VERSION='0.0.1'
APPNAME='tex_test'

bld.set_srcdir('.', '_build_')
bld.set_default_env('main.cache.py')

#import Params
#Params.set_trace(1,1,1)

# we want to build kde programs
from Tools.Tex import texobj

# process subfolders from here
add_subdir('src')

