#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.5'
APPNAME='tex_test'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'

def build(bld):
	# process subfolders from here
	bld.add_subdirs('src')

def configure(conf):
	conf.checkTool(['Tex'])

def set_options(opt):
	pass

