#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

import Configure

VERSION='0.0.1'
APPNAME='qt4_test'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'

def set_options(opt):
	opt.add_option('--qtdir', type='string', help='root of the qt directory', dest='qtdir')
	opt.add_option('--qtlib', type='string', help='root of the qt directory', dest='qtlib')
	opt.add_option('--qtincludes', type='string', help='root of the qt directory', dest='qtincludes')
	opt.add_option('--qtbin', type='string', help='root of the qt directory', dest='qtbin')

def configure(conf):
	conf.checkTool(['g++', 'Qt4'])

def build(bld):
	bld.add_subdirs('src')

