#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

VERSION='0.0.1'
APPNAME='qt4_test'

def set_options(opt):
	opt.add_option('--prefix', type='string', help='installation prefix', dest='prefix')
	opt.add_option('--destdir', type='string', help='destination for install (when creation rpms or debs)', dest='destdir')

	opt.add_option('--qtdir', type='string', help='root of the qt directory', dest='qtdir')
	opt.add_option('--qtlib', type='string', help='root of the qt directory', dest='qtlib')
	opt.add_option('--qtincludes', type='string', help='root of the qt directory', dest='qtincludes')
	opt.add_option('--qtbin', type='string', help='root of the qt directory', dest='qtbin')

def configure():
	conf = create_config()
	conf.checkTool(['g++', 'Qt4'])
	conf.store('main.cache.py')

def setup_build(bld):
	bld.set_dirs('.', '_build_')
	bld.set_default_env('main.cache.py')

def build(bld):
	bld.add_subdir('src')

