#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='test'
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('gcc')

from TaskGen import after, taskgen, feature
@taskgen
@after("apply_lib_vars")
@feature("cc")
def modify_flags(self):
	for task in self.compiled_tasks:
		if task.inputs:
			node = task.inputs[0]
			if node.name == "B.c":
				task.env = task.env.copy()
				task.env.append_unique("_CCDEFFLAGS", "-DMYFLAG")

def build(bld):
	obj = bld.new_task_gen('cc', 'program')
	obj.source = 'A.c B.c'
	obj.target= 'pimpam'

