#! /usr/bin/env python3

top = '.'
out = 'bin'

def options(opt):
	return
	print(opt)

def configure(conf):
	pass

def build(bld):

	print('...')
	print("root", bld.root.abspath(), bld.root)
	print("srcnode", bld.srcnode.abspath(), bld.srcnode)
	print("env", bld.env)

	w = bld.path.find_resource('wscript')
	print("wscript", w.abspath(), w)

	x = bld.path.find_or_declare('xyz.txt')
	print("build file", x.abspath(), x)

	bld(rule='echo hi', always=True)
	bld(rule='touch ${TGT}', target='foo.txt', always=True)

def init(self):
	print('init')

def shutdown(self):
	print('shutdown')


def bar(ctx):
	print("command ok")
