#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008

obj = bld.new_task_gen(
	features = 'cc cprogram',
	packages = 'gtk+-2.0',
	target = 'vala-gtk-example',
	uselib = 'GTK GLIB',
	)

#obj.source='vala-gtk-example.vala'
obj.find_sources_in_dirs('.') # take the sources in the current folder, alternate is setting

