#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008

obj = bld.new_task_gen('cc', 'program')
obj.find_sources_in_dirs('.') # take the sources in the current folder
#obj.source='vala-gtk-example.vala'
obj.packages = 'gtk+-2.0'
obj.target = 'vala-gtk-example'
obj.uselib = 'GTK GLIB'

