#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# and example with file globbing would be better, but for now it will stay like this
install_files('DATADIR', 'icons/hicolor/48x48/apps', 'gnome-hello-logo.png')

#todo
#docbook2man foo.sgml
#cp foo.1 /usr/share/man/man1/
