#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

VERSION='0.0.1'
APPNAME='cfg_test'

bld.set_srcdir('.', '_build_')
bld.set_default_env('main.cache.py')

# stuff we want to load..
from Common import cppobj
from Tools import Ar

add_subdir('src1')

env=create_env()
if env.load('ocaml.cache.py'):
	env.set_alias('ocaml')
	add_subdir('src1')

env=create_env()
if env.load('mylib.cache.py'):
	env.set_alias('mylib')
	add_subdir('src2')


