#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='cpp_test'
top = '.'
out = 'build'

def configure(conf):
	conf.check_tool('local_waf_tool', tooldir='.')

def build(bld):
	bld(source='uh.coin')

