#! /usr/bin/env python
# encoding: utf-8
# Richard Quirk, 2008

import UnitTest

srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('compiler_cxx')

def configure(conf):
	conf.check_tool('compiler_cxx')

	e = conf.create_header_configurator()
	e.mandatory = 1
	e.name = 'cppunit/CompilerOutputter.h'
	e.run()

	# This will create a uselib entry CPPUNIT
	e = conf.create_library_configurator()
	e.mandatory = 1
	e.name = 'cppunit'
	e.run()
	e.name = 'dl'
	e.run()


def build(bld):
	# process subfolders from here
	bld.add_subdirs('src tests')

def shutdown():
	ut = UnitTest.unit_test()
	ut.change_to_testfile_dir = True
	# normally only seen if we run "waf check"
	ut.run_if_waf_does = 'build'
	ut.run()
	ut.print_results()
