#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='simple_tool'
srcdir = '.'
blddir = 'build'

import TaskGen
TaskGen.declare_chain(
	name = 'dang',
	action = '${COPY} ${SRC} ${TGT}',
	ext_in = '.coin',
	ext_out = '.cpp',
	reentrant = 0
)

def set_options(opt):
	pass

def configure(conf):
	import os
	conf.env['COPY'] = os.getcwd() + os.sep + "cp.py"

def build(bld):
	bld.new_task_gen(source="uh.coin")

	#foo = TaskGen.task_gen()
	#foo.source = "uh.coin"

