#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# The first example is a simple program
obj=ocamlobj('all')
obj.source='''
somemodule.ml main.ml
'''
#obj.includes='. src'
obj.target='camlprog'

