#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build(bld):
	# The first example is a simple program
	obj = bld.createObj('ocaml', 'all')
	obj.source='''
	somemodule.ml main.ml
	'''
	obj.includes='.'
	obj.target='camlprog'

