#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='d_test'

import Params

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.tool_options('dmd')

def configure(conf):
	conf.check_tool('dmd')
	if not conf.env['D_COMPILER']:
		conf.check_tool('gdc')
	if not conf.env['D_COMPILER']:
		Params.fatal('This demo requires a d compiler! (either dmd or gdc)')
	conf.env['LIB_PTHREAD'] = ['pthread']

def build(bld):
	bld.add_subdirs('src2')

	obj = bld.create_obj('d', 'staticlib')
	obj.source = '''
	testlib/code.d
	'''
	obj.importpath = '.'
	obj.name = 'testlib'
	obj.target = 'testlib'

	obj = bld.create_obj('d', 'program')
	obj.source = '''
	example.d
	'''
	obj.target = 'd_test'
	obj.uselib_local = 'testlib'
	obj.uselib = 'PTHREAD'
