#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

VERSION='0.0.1'
APPNAME='d_test'

top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_d')

def configure(conf):
	conf.check_tool('compiler_d')
	conf.env.LIB_PTHREAD = ['pthread']
	conf.check_dlibrary()

def build(bld):
	if bld.env.DLIBRARY != 'tango':
		bld.add_subdirs('src')

		# here is how to use the object-oriented notation
		bld(
			features     = 'd dstaticlib',
			source       = 'testlib/code.d',
			includes     = '.',
			name         = 'testlib',
			target       = 'testlib')

		bld(features     = 'd dprogram',
			source       = 'example.d',
			target       = 'd_test',
			uselib_local = 'testlib',
			uselib       = 'PTHREAD',
			includes     = '.')

	else:
		# bad pun hidden
		bld(features='d dprogram', source='foo.d', target='bar', includes='.')

