#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen('cxx', 'program')
obj.find_sources_in_dirs('.')
obj.uselib = 'CPPUNIT'
obj.uselib_local = 'unittestmain useless'
obj.unit_test = 1
obj.target = 'unit_test_program'

