#! /usr/bin/env python
# encoding: utf-8

VERSION='0.0.1'
APPNAME='vala_test'

top = '.'
out = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('gcc vala')
	conf.check_tool('valadoc', tooldir='.')

def build(bld):
	bld(
		features='valadoc',
		output_dir = './doc',
		package_name = 'vala_test',
		package_version = '0.0.1',
		protected = True,
		force = True,
		files = bld.path.ant_glob (incl='**/*.vala', flat=False)
	)

