#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='cpp_test'
srcdir = '.'
blddir = 'build'

def set_options(opt):
	opt.add_option('--exe', action='store_true', default=False, help='Execute the program after it is compiled')

def configure(conf):
	pass
def build(bld):
	pass
def shutdown():
	import Params
	print "shutdown called with --exe command-line", Params.g_options.exe

	if Params.g_install:
		print "shutdown when running install or uninstall!!!"

	# import os
	# os.popen("./build/default/foo --help").read()

