#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build ( bld ) :
        obj = bld.createObj('tex' , type='latex') # type could be pdflatex
        obj.source = 'document.ltx' # mandatory, the source

	# optional parameters
        obj.outs   = 'ps' # we want a postscript output too - 'ps pdf' works too
	obj.prompt = 1 # put 0 for the batchmode (conceals the debug output)
	obj.deps   = 'crossreferencing.ltx' # use this to give dependencies directly
