#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build ( bld ) :

	# we can modify the way tex files are scanned
	import re, tex
	tex.tex_regexp = re.compile('^\\\\bringin{(.*)}', re.M)

	# now create your tex object for compiling the files
        obj = bld.create_obj('tex' , type='latex') # type could be pdflatex
        obj.source = 'document.ltx' # mandatory, the source

	# optional parameters
        obj.outs   = 'ps' # we want a postscript output too - 'ps pdf' works too
	obj.prompt = 1 # put 0 for the batchmode (conceals the debug output)
	obj.deps   = 'crossreferencing.ltx' # use this to give dependencies directly
