#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build ( bld ) :
        obj = bld.createObj('tex' , 'latex')
        obj.source = 'document.ltx'
        obj.outs   = 'ps'
	obj.prompt = 1 # put 0 for the batchmode
