#! /usr/bin/env python

def build(bld):
	o = bld.create_obj('cc', 'program')
	o.source = 'main.c'
	o.target = 'blah'
	o.meths.append('process_marshal')
	o.add_marshal_file('marshal.list', 'test_prefix', '--header')

