#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

"""
demonstrate how to compile tasks at once by collecting all the .c files
"""

VERSION='0.0.1'
APPNAME='cc_test'
top = '.'
out = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('gcc')
	conf.check_tool('batched_cc', tooldir='.')

def build(bld):
	bld(features='cc cprogram', source='main.c foo.c bar.c', target='test', includes='.')

def shutdown():
	import os
	#os.popen('echo "">> a/a.h').read()

