#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='test'
srcdir = '.'
blddir = 'build'

import Options

def set_options(opt):
	# options
	opt.add_option('--fr', action='store_true', default=False, help='french version')
	opt.add_option('--es', action='store_true', default=False, help='spanish version')

def configure(conf):
	# persistent
	conf.env.ES = not (not Options.options.es)

def build(bld):
	if Options.options.fr:
		bld.add_subdirs("fr")
	if bld.env.ES:
		bld.add_subdirs("es")

