#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# Creates a simple program
# This file is not a module, and all the code
# from it will be executed upon compile step
#
# This is really the content of a "def build(bld):" function definition
#
# By contrast, only functions can be defined in a wscript
#

obj = bld(
	features = 'cxx cprogram',
	source = 'main.cpp',
	includes = '. ../src',
	uselib_local = 'unique1 john',
	target = 'testapp2')

# demonstrate using of custom linker for an object
# (BTW: the '--start-group' and '--end-group' may resolve circular references between libraries.)
#import Task
#custom_link_str = '${LINK_CXX} ${CXXLNK_SRC_F}${SRC} ${CXXLNK_TGT_F}${TGT} -Wl,--start-group ${LINKFLAGS} -Wl,--end-group'
#Task.simple_task_type('custom_link', custom_link_str, color='YELLOW', ext_in='.o')
#obj.link = 'custom_link'

