#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='cc_test'

srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('g++')
	conf.check_tool('doxygen', tooldir='.')

def build(bld):
	# Note: Doxgen parameters may be passed using pars attribute
	#       e.g. pars={'EXCLUDE_PATTERNS':'*.babu'}
	bld(features='doxygen',
			doxyfile='test.conf',
			doxy_tar='docs.tar.bz2',
			install_to='${PREFIX}/share/doc/doxy_test/manual')

