#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005 (ita)

"""
obj = kdeobj()
obj.source = 'window.cpp'
obj.target = 'window'
obj.uselib = 'QT QTCORE QTGUI QTOPENGL'
obj.include = './_build_/src/test/ ./_build_/src/'
obj.depends('firstobj')
"""

def build(bld):
	pass

