#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# provides a demo for different objects built using different variants

lib1 = bld.new_task_gen(
	features='cc cshlib',
	source = 'lib1.c',
	target = 'lib1')

prog_in_variant1 = bld.new_task_gen(
	features = 'cxx cprogram',
	source = 'src1.c',
	target = 'myprog',
	uselib_local = 'lib1')

# this second library in the variant 'debug' (another folder)
#will not link against a c library
prog2 = prog_in_variant1.clone('debug')
prog2.uselib_local = ''

