#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# provides a demo for different objects built using different variants

lib_in_variant1 = bld.create_obj('cc', 'shlib')
lib_in_variant1.source='''
lib1.c
'''
lib_in_variant1.includes      = '.'
lib_in_variant1.target        = 'lib1'
lib_in_variant1.name          = 'lib1'


prog_in_variant1 = bld.create_obj('cpp', 'program')
prog_in_variant1.source='''
src1.c
'''
prog_in_variant1.includes     = '.'
prog_in_variant1.target       = 'myprog'
prog_in_variant1.uselib_local = 'lib1'


prog2 = prog_in_variant1.clone('variant2')
prog2.uselib_local = ''

# until a better clone scheme is provided
prog2.p_compiletasks = []

