#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

APPNAME='kde3app'
VERSION='0.0.1'

bld.set_dirs('.', '_build_')
bld.set_default_env('main.cache.py')

# TODO: make it possible to run without scanning src/appdata
# scan the folders
#bld.scandirs('src')

# we want to build kde programs
import Tools
from Tools.KDE3 import kdeobj, kde_translations, kde_documentation
from Common import install_files, install_as

add_subdir('src')

