#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

import os
import Configure

APPNAME='kde3app'
VERSION='0.0.1'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'
cachedir = '_build_/cache'

def set_options(opt):
	opt.add_option('--prefix', type='string', help='installation prefix', dest='prefix')
	opt.add_option('--destdir', type='string', help='destination for install (when creation rpms or debs)', dest='destdir')

def configure(conf):
	conf.checkTool(['g++', 'KDE3'])
	conf.checkHeader('dlfcn.h','HAVE_DLFCN_H')
	conf.addDefine('TEST_DEFINE', '345')
	conf.writeConfigHeader('config.h')

def build(bld):
	bld.add_subdir('src')

