#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

APPNAME='kde3app'
VERSION='0.0.1'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'

def set_options(opt):
	opt.add_option('--prefix', type='string',
		help='installation prefix',
		dest='prefix')
	opt.add_option('--want-rpath', action='store_true',
		dest='want_rpath',
		default=True,
		help='turn rpath off or on')

	for i in "execprefix datadir libdir kdedir kdeincludes kdelibs qtdir qtincludes qtlibs libsuffix".split():
		opt.add_option('--'+i, type='string', default='', dest=i)

def configure(conf):
	conf.checkTool(['g++', 'KDE3'])
	conf.env['CXXFLAGS_QT']=['-DQT_THREAD_SUPPORT']
	conf.checkHeader('dlfcn.h','HAVE_DLFCN_H')
	conf.addDefine('TEST_DEFINE', '345')
	# check for libkcal using the KDECORE variables
	#conf.checkLibrary('kcal', uselib='KDECORE')
	conf.writeConfigHeader('config.h')

def build(bld):
	bld.add_subdirs('src')

