#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='simple_tool'
srcdir = '.'
blddir = 'build'

import TaskGen 
TaskGen.declare_chain(
	name = 'a',
	action = '${COPY} ${SRC} ${TGT}',
	ext_in = '.input',
	ext_out = '.a',
	prio = 40,
)

TaskGen.declare_chain(
	name = 'b',
	action = '${COPY} ${SRC} ${TGT}',
	ext_in = '.a',
	ext_out = '.b',
	prio = 42,
)

TaskGen.declare_chain(
	name = 'c',
	action = '${COPY} ${SRC} ${TGT}',
	ext_in = '.b',
	ext_out = '.c',
	reentrant = 0,
	prio = 44
)

def set_options(opt):
	pass

def configure(conf):
	import os
	conf.env['COPY'] = os.getcwd() + os.sep + "cp.py"

def build(bld):
	TaskGen.task_gen(source="uh.input")

	#foo = TaskGen.task_gen()
	#foo.source = "uh.coin"

