#! /usr/bin/env python
# encoding: utf-8
# Thomas Zellman 2009

srcdir = '.'
blddir = 'target'

def set_options(opt):
    opt.tool_options('compiler_cc')
    opt.tool_options('javaw')

def configure(conf):
    conf.check_tool('compiler_cc')
    conf.check_tool('java')
    conf.check_jni_headers()

def build(bld):
    bld.new_task_gen(features='javac seq', source_root='src/java')
    bld.new_task_gen(features='jar seq', basedir='src/java',
					destfile='stringUtils.jar')

    lib = bld.new_task_gen(features='cc cshlib',
							includes='src/jni/include',
							target='stringUtils',
							uselib='JAVA')
    lib.find_sources_in_dirs('src/jni/source')

