#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2009 (ita)

# process .in files with intl_tool

bld.new_task_gen(
	features = 'intltool_in',
	source   = 'gnome-test.schemas.in',
	install_path = '${PREFIX}/etc/gconf/schemas',
	podir    = '../po',
	flags    = '-s')

bld.new_task_gen(
	features = 'intltool_in',
	source   = 'gnome-test.desktop.in',
	install_path = '${PREFIX}/share/gnome/autostart',
	podir    = '../po',
	flags    = '-d')
