#! /usr/bin/env python
# encoding: utf-8

bld(
	features = 'cxx cprogram test',
	source   = 'AccumulatorTest.cpp',
	target   = 'unit_test_program',
	uselib   = 'CPPUNIT',
	uselib_local = 'unittestmain useless',
	ut_cwd   = bld.path.find_dir('.').abspath()
)

