#! /usr/bin/env python3.1

import os
import Node, Build, Utils, Logs

def tt(msg, result, expected):
	color = 'RED'
	if result == expected:
		color = 'GREEN'
	Logs.pprint(color, msg.ljust(20) + " " + result)

def configure(ctx):
	pass

def test(ctx):
	bld = Build.BuildContext()
	bld.prepare()

	dir = bld.root.make_node(os.getcwd().split('/'))
	p = dir.parent

	tt('dir printed', str(dir), os.getcwd())
	tt('parent', str(p), os.path.split(os.getcwd())[0])
	tt('path_from', dir.path_from(p), os.path.split(os.getcwd())[1])
	tt('path_from (reverse)', p.path_from(dir), '..')
	tt('same path', p.path_from(p), '.')
	tt('same_root', bld.root.path_from(bld.root), '.')

	d1 = dir.make_node(['a', 'b'])
	d2 = dir.make_node(['c', 'd'])

	tt('d1 from d2', d1.path_from(d2), '../../a/b')
	tt('d2 from d1', d2.path_from(d1), '../../c/d')



