#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy 2009

# ctx == conf
# (do not use conf, it will be deprecated in waf 1.6)

ctx.write_config_header('another_config.h', env=conf.all_envs['default'])
ctx.write_config_header('another_config.h', env=conf.all_envs['debug'])

