#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005 (ita)

def build(bld):

	# the functional syntax is equivalent to the object-oriented one
	obj = bld.new_task_gen(
		features=['qt4', 'cprogram', 'cxx'],
		uselib = 'QTCORE QTGUI QTOPENGL QTSVG',
		target = 'window',
		includes = 'test .',
		defines="WAF=1", # add a define around foo.moc
	)

	## the sources can be given manually
	## or found automatically in the directories specified
	#obj.source = 'window.cpp glwidget.cpp main.cpp textures.qrc'
	obj.find_sources_in_dirs('.')

	#obj.lang='fr es' <- find_sources_in_dirs sets this
	obj.langname='langs'
	#obj.update=1 # <- call waf --translate to update the translation files


	bld.add_subdirs('test')

