#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='cc_test'

srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('g++')
	conf.check_tool('doxygen', tooldir='.')

def build(bld):
	#bld.rescan(bld.path.find_dir('docu_out'))
	#bld.new_task_gen(features='cxx cprogram', source='a.cpp b.cpp subdir/c.cpp', target='test')
	bld.new_task_gen(features='doxygen', doxyfile='test.conf')#, doxy_tar='docs.tar.bz2')

