#!/usr/bin/env python
# encoding: utf-8
# Tom Wambold tom5760 gmail

top = '.'
out = 'build'

def configure(ctx):
	ctx.check_tool('go')

def build(ctx):
	ctx(
		features = 'go gopackage',
		target   = 'other',
		source   = [
			'other/a.go',
			'other/b.go',
		],
	)

	ctx(
		features = 'go goprogram',
		target   = 'test',
		uselib_local = 'other',
		source   = 'main.go',
		includes = '.',
	)

