#! /usr/bin/env python
# encoding: utf-8

def build(bld):
	"""
	obj = bld.new_task_gen('docbook')
	obj.type = 'pdf'
	obj.source='''
	docbook.xml
	docbooks.sgml
	docbookd.docbook
	'''
	obj.stylesheet='docbook-pdf.xsl'

	# with pdf, the stylesheet provided will not work, however, using this one will:
	#obj.stylesheet = "/usr/share/xml/docbook/stylesheet/nwalsh/current/fo/docbook.xsl"
	"""

	obj = bld.new_task_gen('docbook')
	obj.type = 'html'
	obj.source='''
	docbook.xml
	docbooks.sgml
	docbookd.docbook
	'''
	obj.stylesheet='docbook-html.xsl'

