#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='test'
top = '.'
out = 'build'

def init(ctx):
	print "-> init called"
def set_options(opt):
	pass
def configure(conf):
	pass
def build(bld):
	pass
def shutdown(ctx):
	pass

