#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2007-2010 (ita)

bld(
	features='xml_to',
	source = 'gnome-power-manager.xml',
	target = 'gnome-power-manager.html',
	xslt = 'config.xsl',
	inst_var = 'PREFIX',
	inst_subdir = 'usr/doc/PackageKit/docs',
)

