#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2007 (ita)

obj=bld.new_task_gen('xmlto')
obj.source = 'gnome-power-manager.xml'
obj.target = 'gnome-power-manager.html'
obj.xslt = 'config.xsl'
obj.inst_var = 'PREFIX'
obj.inst_subdir = 'usr/doc/PackageKit/docs'

