#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2006 (ita)

VERSION='0.0.1'
APPNAME='qt3_test'

# these variables are mandatory,
srcdir = '.'
blddir = '_build_'

def set_options(opt):
	opt.tool_options('Qt3')

def configure(conf):
	conf.check_tool('g++ Qt3')
	#conf.write_config_header()
def build(bld):
	obj = bld.create_obj('qt3', 'program')

	obj.source = 'main.cpp lcdrange.cpp'
	obj.uselib = 'QT3'
	obj.target = 'qt3test'
	obj.includes = '.'
