#! /usr/bin/env python

APPNAME = 'crazy_rpath'
VERSION = '1.0'

top = '.'
out = 'bin'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_tool('morelink', tooldir='.')

def build(bld):
	bld(features='cc cshlib', source='foo.c', target='foo', rpath='/usr/lib')
	bld(features='cc cshlib', source='foo.c', target='bar', rpath='/usr/lib', vnum='1.2.3')
	bld(features='cc cprogram', source='main.c', target='app', uselib_local='bar')
