#! /usr/bin/env python

import sys
from optparse import OptionParser
import fileinput
try:
	from hashlib import md5
except:
	from md5 import md5


def main():
	parser = OptionParser()
	parser.add_option("", "--output-md5", metavar="FILE", dest="md5_out",
					  help="output the md5sum to a file")
	parser.add_option("", "--input", metavar="FILE", dest="input",
					  help="read from the given input file")
	(options, args) = parser.parse_args()
	sys.argv = args

	if options.md5_out:
		m = md5()
	else:
		m = None

	print "-------------------- BEGIN ------------------------------"
	if options.input:
		input = file(options.input)
	else:
		input = fileinput.input()
	for line in input:
		print line,
		if m:
			m.update(line)
	print "--------------------- END ------------------------------"

	if options.md5_out:
		f = file(options.md5_out, "w")
		f.write(m.hexdigest())
		f.close()


if __name__ == '__main__':
	main()
