#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

# Creates a simple program with c++ and c sources as input
# compile with the appropriate compilers and link with g++

out = bld(
	features = 'cxx cc cprogram',
	source = 'a.cpp b.c',
	target = 'hybrid')

