#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

from sconpat import *

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='compat_test'


# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

# scons does not provide colors
import Params
Params.reset_colors()

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	bld = Builder(action = 'cat $SOURCE > $TARGET')
	env = Environment(BUILDERS = {'Foo' : bld})
	env.Foo('foo.out', 'foo.in')

