#! /usr/bin/env python
# encoding: UTF-8
# Petar Forai

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='swig_test'

# these variables are mandatory,
srcdir = '.'
blddir = 'build'

def init():
	pass

def set_options(opt):
	opt.tool_options('gcc')
	opt.tool_options('python')

def configure(conf):
	conf.check_tool('g++ swig python')

	conf.env['SWIGFLAGS']='-c++ -python -dump_classes'
	conf.env['CXXFLAGS']='-Wall -g -O0 -pipe'
	conf.check_python_version((2,4,2))
	conf.check_python_headers()

def build(bld):
	obj = bld.create_obj('cpp','program','pyembed')
	obj.source = 'swigtooldemo.cpp swigtooldemo.swig'
	obj.target = 'swigdemo'
	obj.include = '.'
def shutdown():
	pass


