#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2008 (ita)

# and example with file globbing would be better, but for now it will stay like this
bld.install_files('${DATADIR}/icons/hicolor/48x48/apps', 'gnome-hello-logo.png')

