#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# 1. A simple program
obj=cppobj('program')
obj.source='''
a1.cpp
b1.cpp b2.cpp
main.cpp
'''
obj.includes='. src'
obj.target='testprogram'

# 2. A shared library
# The extension (.so) is added automatically
obj=cppobj('shlib')
obj.source='''
a1.cpp
b1.cpp b2.cpp
'''
obj.includes='. src'
obj.target='testshlib'

# 3. A static library
# The extension (.a) is added automatically
obj=cppobj('staticlib')
obj.source='''
c1.cpp
'''
obj.includes='. src'
obj.target='teststaticlib'


