#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# notes:
# 1. We think it is good to give names to our objects
# 2. In practice something like 'libkdegames' might do it better
# 3. Any coincidence with characters living or dead is purely coincidental

def build(bld):
	import Params
	print "command-line parameter meow is ", Params.g_options.meow

	# 1. A simple program
	obj = bld.create_obj('cpp', 'program')
	obj.source='''
	a1.cpp
	b1.cpp b2.cpp
	main.cpp
	'''
	obj.includes='.'
	obj.target='testprogram'

	# 2. A shared library
	# The extension (.so) is added automatically
	obj = bld.create_obj('cpp', 'shlib')
	obj.source='''
	a1.cpp
	b1.cpp b2.cpp
	'''
	obj.includes     = '.'
	#obj.name         = 'peter'
	obj.target       = 'testshlib'
	obj.install_in   = 'SOME_INSTALL_DIR'

	# 3. A static library
	# The extension (.a) is added automatically
	obj = bld.create_obj('cpp', 'staticlib')
	obj.source='''
	c1.cpp
	'''
	obj.includes     = '.'
	obj.name         = 'tony'
	obj.target       = 'teststaticlib'

	# 4. Another shared library
	obj = bld.create_obj('cpp', 'shlib')
	obj.source='''
	d1.cpp
	'''
	obj.includes     = '.'
	obj.target       = 'shlib1'
	obj.name         = 'john'
	obj.want_libtool = 1
	obj.vnum         = '1.2.3'

	# 5. A program that links against shlib1
	obj = bld.create_obj('cpp', 'program')
	obj.source='''
	e1.cpp
	'''
	obj.includes     = '.'
	obj.uselib       = 'MYPROG'
	obj.uselib_local = 'tony john testshlib' # 'tony john peter' # look for 'peter' above
	obj.target       = 'program_dyn_linked'

	# IMPORTANT WARNING:
	# uselib_local expects *names*, that is, the field obj.name
	# by simplicity, when there is no ambiguity: obj.target == obj.name

	# installing files, headers ..
	install_files('PREFIX', 'include', 'a1.h')
	#install_as('PREFIX', 'dir/ahoy.h', 'a1.h')

def set_options(opt):
	# options defined if src/ was to be compiled as a standalone module
	opt.add_option('--meow', type='string', help='option hidden in the src module', dest='meow')

def configure(conf):
	print "sub-configuration file called (demo)"

