#! /usr/bin/env python

def build(bld):
	o = bld.new_task_gen('cc', 'program')
	o.source = 'main.c'
	o.target = 'blah'
	o.add_enums_from_template(source='a.h b.h', target='prodi.h', template='x.in')

