#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='docbook_test'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	return

def configure(conf):
	# look in the script below for the check_tool call
	conf.check_tool('docbook', tooldir='.')

def build(bld):
	# process subfolders from here
	bld.add_subdirs('doc')
	return

