#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.1'
APPNAME='simple_tool'
srcdir = '.'
blddir = 'build'

import os
import TaskGen
TaskGen.declare_chain(
	name = 'dang',
	action = '${COPY} ${SRC} ${TGT}',
	ext_in = '.coin',
	ext_out = '.cpp',
	reentrant = 0
)

def set_options(opt):
	pass

def configure(conf):
	cmd = os.getcwd() + os.sep + "cp.py"
	conf.env['COPY'] = cmd

	env2 = conf.env.copy()
	conf.set_env_name('debug', env2)
	conf.setenv('debug')

	conf.env['COPY'] = "echo 'the command to execute is ' %s && %s" % (cmd, cmd)

def build(bld):
	foo = TaskGen.task_gen()
	foo.source = "uh.coin"
	#foo.env = bld.env_of_name("default")
	foo.env = bld.env_of_name("debug")

