#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

# archive creation

VERSION='0.0.1'
APPNAME='archiver_test'
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.env['TAR'] = 'tar'
	conf.check_tool('archiver', tooldir='.')

def build(bld):
	for x in "abcd":
		bld.new_task_gen(
		source='wscript',
		target='%s.txt' % x,
		rule='cp ${SRC} ${TGT}',
		before='tar')

	bld.new_task_gen(
		features='archiver',
		target='foo.tar.bz2',
		taropts='-cjf',
		excludes='.lock-wscript')

