#!/usr/bin/env python
# encoding: utf-8

def build(bld):
	# to compile in c or c++ mode, uncomment the appropriate line below:
	#mode = 'cxx'
	mode = 'cc'

	obj = bld.new_task_gen(mode, 'program')
	#obj.source='''
	#main.c
	#calc.l
	#calc.y
	#'''
	obj.find_sources_in_dirs('.')
	obj.includes='.'
	obj.target='calc'
	obj.uselib="CALC"
