#!/usr/bin/env python
# encoding: utf-8

def build(bld):
	# to compile in c or cpp mode, uncomment the appropriate line below:
	mode = 'cpp'
	#mode = 'cc'

	obj = bld.createObj(mode, 'program')
	obj.source='''
	main.cc
	calc.l
	calc.yc
	'''
	obj.includes='.'
	obj.target='calc'
	obj.uselib="CALC"
