#! /usr/bin/env python
# encoding: utf-8
# Gustavo Carneiro, 2007

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='python_test'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('python')

def build(bld):
	obj = bld.create_obj('py')
	obj.pyo = 1
	obj.source = 'foo.py'
