#! /usr/bin/env python
# encoding: utf-8
# Gustavo Carneiro, 2007

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='python_test'

# these variables are mandatory ('/' are converted automatically)
srcdir = '.'
blddir = 'build'

def set_options(opt):
	pass

def configure(conf):
	conf.check_tool('python gcc')
	conf.check_python_version((2,4,2))
	conf.check_python_headers()

def build(bld):
	# first compile a few pyc files
	obj = bld.create_obj('py')
	obj.pyo = 1
	#obj.source = 'foo.py'
	obj.find_sources_in_dirs('.')

	# then a c extension module
	obj = bld.create_obj('cc', 'shlib')
	obj.source = 'spammodule.c'
	obj.target = 'spam'
	obj.uselib = 'PYEXT'
	obj.env['shlib_PREFIX'] = ''
	obj.install_in = 'PYTHONDIR'

	# then a c program
	obj = bld.create_obj('cc', 'program')
	obj.source = 'test.c'
	obj.target = 'test'
	obj.uselib = 'PYEMBED'

def shutdown():
	import os
	print os.popen('build/default/test').read()

