#!/usr/bin/env python
# encoding: ISO8859-1
# Thomas Nagy, 2010

top = '.'
out = 'build'

def set_options(opt):
	opt.tool_options('compiler_cc')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_tool('cuda', tooldir='.')

def build(bld):
	t = bld(
		features = 'cc cprogram',
		source   = 'test.cu main.c',
		target   = 'app',
		uselib = 'CUDA')

	t.env.LIB_CUDA = ['cuda', 'cudart']
	t.env.LIBPATH_CUDA = ['/usr/local/cuda/lib64']
	return
	t.env.CC = 'nvcc'
	t.env.LINK_CC = 'nvcc'

	import TaskGen
	TaskGen.task_gen.mappings['.cu'] = TaskGen.task_gen.mappings['.c']

#t.env.CUDAFLAGS = '-deviceemu'
#CUDAFLAGS=-deviceemu
#CUDAFLAGS=--ptxas-options="-v"
#CUDAFLAGS=--ptxas-options="-v -maxrregcount=10"

